import express, { Request, Response } from 'express';
// ... existing imports ...

const app = express();
// ... existing code ...

// Remove the report endpoint and continue with other endpoints
// ... rest of the code ... 